# Generated by Django 5.1.6 on 2025-05-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0006_rename_telegram_coin_discord_remove_trade_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
    ]
