# Generated by Django 5.1.6 on 2025-05-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0007_alter_coin_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coindrcscore',
            name='audit_completed',
        ),
        migrations.RemoveField(
            model_name='coindrcscore',
            name='audit_score',
        ),
        migrations.RemoveField(
            model_name='coindrcscore',
            name='price_stability_score',
        ),
        migrations.RemoveField(
            model_name='coindrcscore',
            name='verified_contract',
        ),
        migrations.AddField(
            model_name='coindrcscore',
            name='holder_retention_months',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coindrcscore',
            name='last_daily_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coindrcscore',
            name='last_monthly_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coindrcscore',
            name='last_price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='coindrcscore',
            name='last_recorded_holders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coindrcscore',
            name='last_recorded_price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='coindrcscore',
            name='max_volume_recorded',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='coindrcscore',
            name='price_breakouts_per_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coindrcscore',
            name='team_abandonment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coindrcscore',
            name='token_abandonment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coindrcscore',
            name='score',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='developerscore',
            name='score',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='traderscore',
            name='score',
            field=models.IntegerField(default=200),
        ),
        migrations.AddIndex(
            model_name='coindrcscore',
            index=models.Index(fields=['last_monthly_update'], name='systems_coi_last_mo_6e83db_idx'),
        ),
    ]
