# Generated by Django 5.1.6 on 2025-05-26 11:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0008_remove_coindrcscore_audit_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coindrcscore',
            name='trade_volume_24h',
        ),
        migrations.RemoveField(
            model_name='developerscore',
            name='coins_active_24h_plus',
        ),
        migrations.RemoveField(
            model_name='developerscore',
            name='coins_created_count',
        ),
        migrations.RemoveField(
            model_name='developerscore',
            name='coins_rugged_count',
        ),
        migrations.RemoveField(
            model_name='developerscore',
            name='highest_market_cap',
        ),
        migrations.AddField(
            model_name='coindrcscore',
            name='last_biweekly_update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coindrcscore',
            name='pump_and_dump_activity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='developerscore',
            name='abandoned_projects',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='developerscore',
            name='rug_pull_or_sell_off',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='developerscore',
            name='successful_launch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='traderscore',
            name='held_tokens_per_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='traderscore',
            name='quick_pump_and_dumps_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='traderscore',
            name='sniping_and_dumps_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coindrcscore',
            name='last_monthly_update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coindrcscore',
            name='score',
            field=models.IntegerField(default=150),
        ),
        migrations.AlterField(
            model_name='developerscore',
            name='score',
            field=models.IntegerField(default=150),
        ),
        migrations.AlterField(
            model_name='traderscore',
            name='score',
            field=models.IntegerField(default=150),
        ),
        migrations.AddIndex(
            model_name='coindrcscore',
            index=models.Index(fields=['last_biweekly_update'], name='systems_coi_last_bi_19eba2_idx'),
        ),
    ]
