# Generated by Django 5.1.6 on 2025-05-26 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0009_remove_coindrcscore_trade_volume_24h_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoinRugFlag',
        ),
    ]
