# Generated by Django 5.1.6 on 2025-05-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0010_delete_coinrugflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='ath',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='coindrcscore',
            name='successful_token',
            field=models.BooleanField(default=False),
        ),
    ]
