# Generated by Django 5.1.6 on 2025-05-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0011_coin_ath_coindrcscore_successful_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderscore',
            name='avg_holding_time_hours',
        ),
        migrations.RemoveField(
            model_name='traderscore',
            name='coins_held_count',
        ),
        migrations.RemoveField(
            model_name='traderscore',
            name='held_tokens_per_month',
        ),
        migrations.RemoveField(
            model_name='traderscore',
            name='profitable_trades_percent',
        ),
        migrations.RemoveField(
            model_name='traderscore',
            name='quick_dumps_count',
        ),
        migrations.RemoveField(
            model_name='traderscore',
            name='quick_pump_and_dumps_count',
        ),
        migrations.RemoveField(
            model_name='traderscore',
            name='sniping_and_dumps_count',
        ),
        migrations.RemoveField(
            model_name='traderscore',
            name='trades_count',
        ),
        migrations.AddField(
            model_name='coindrcscore',
            name='last_held_percent',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24),
        ),
        migrations.AddIndex(
            model_name='coindrcscore',
            index=models.Index(fields=['score', 'successful_token'], name='systems_coi_score_8997a8_idx'),
        ),
        migrations.AddIndex(
            model_name='coindrcscore',
            index=models.Index(fields=['coin', 'last_monthly_update'], name='systems_coi_coin_id_326ea9_idx'),
        ),
        migrations.AddIndex(
            model_name='coindrcscore',
            index=models.Index(fields=['team_abandonment', 'token_abandonment'], name='systems_coi_team_ab_c3e07b_idx'),
        ),
    ]
