# Generated by Django 5.1.6 on 2025-05-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0012_remove_traderscore_avg_holding_time_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='score',
            field=models.IntegerField(default=150),
        ),
    ]
