# Generated by Django 5.1.6 on 2025-06-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0014_developerscore_no_rugs_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='coin_amount',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='trade',
            name='sol_amount',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
