# Generated by Django 5.1.6 on 2025-06-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0015_alter_trade_coin_amount_alter_trade_sol_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='decimal',
            field=models.IntegerField(default=3, max_length=3),
        ),
    ]
