# Generated by Django 5.1.6 on 2025-06-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0016_coin_decimal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='decimal',
        ),
        migrations.AddField(
            model_name='coin',
            name='decimals',
            field=models.SmallIntegerField(default=9),
        ),
    ]
