# Generated by Django 5.1.6 on 2025-06-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0017_remove_coin_decimal_coin_decimals'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='price_per_token',
            field=models.IntegerField(default=25),
        ),
    ]
