# Generated by Django 5.1.6 on 2025-03-19 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_auth', '0002_remove_coin_total_amount_held_coin_current_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='ticker',
        ),
    ]
