# Generated by Django 5.1.6 on 2025-03-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_auth', '0003_remove_coin_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('COIN_CREATE', 'Coin Creation')], max_length=14),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['user'], name='wallet_auth_user_id_f24b21_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['coin'], name='wallet_auth_coin_id_89c52a_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['created_at'], name='wallet_auth_created_1aa713_idx'),
        ),
    ]
