# Generated by Django 5.1.6 on 2025-04-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_auth', '0004_alter_trade_trade_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='symbol',
        ),
        migrations.AddField(
            model_name='coin',
            name='ticker',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
