# Generated by Django 5.1.6 on 2025-04-28 23:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_auth', '0005_remove_coin_symbol_coin_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='ticker',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
